# Generated by Django 6.0.5 on 2026-06-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', max_length=100),
        ),
    ]
