# Generated by Django 6.0.5 on 2026-06-06 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversion',
            new_name='conversation',
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
