# Generated by Django 6.0.5 on 2026-06-09 07:16

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_rename_conversion_message_conversation_and_more"),
    ]

    operations = [
        VectorExtension(),
    ]
