from typing import Any, Dict, List, Optional

from ..exception import PromptBuilderError


class PromptBuilder:
    """
    Build provider-agnostic chat prompts.

    Final structure:

    System Prompt
    Context
    Recent History
    Current User Query
    """

    ALLOWED_ROLES = {
        "system",
        "user",
        "assistant",
        "tool",
    }

    def build(
        self,
        system_prompt: str,
        user_message: str,
        history: Optional[List[Dict[str, Any]]] = None,
        context: Optional[str] = None,
    ) -> List[Dict[str, str]]:
        """
        Build normalized messages for the LLM.

        Args:
            system_prompt:
                Global instructions.

            user_message:
                Current user query.

            history:
                Recent chat history.

            context:
                Context generated by ContextBuilder.

        Returns:
            Provider-agnostic messages.
        """

        if not user_message or not user_message.strip():
            raise PromptBuilderError("User message cannot be empty.")

        messages: List[Dict[str, str]] = []

        # Main system prompt
        if system_prompt and system_prompt.strip():

            messages.append(
                {
                    "role": "system",
                    "content": system_prompt.strip(),
                }
            )

        # Inject retrieved context
        if context and context.strip():

            messages.append(
                {
                    "role": "system",
                    "content": (
                        "Use the following contextual information "
                        "to answer the user's question accurately. "
                        "Prioritize legal reference material when relevant.\n\n"
                        f"{context.strip()}"
                    ),
                }
            )

        # Recent conversation history
        for message in history or []:

            self._validate_message(message)

            messages.append(
                {
                    "role": message["role"],
                    "content": str(message["content"]).strip(),
                }
            )

        # Current query
        messages.append(
            {
                "role": "user",
                "content": user_message.strip(),
            }
        )

        return messages

    def _validate_message(
        self,
        message: Dict[str, Any],
    ) -> None:

        if not isinstance(message, dict):
            raise PromptBuilderError("History message must be a dictionary.")

        role = message.get("role")
        content = message.get("content")

        if role not in self.ALLOWED_ROLES:
            raise PromptBuilderError(f"Invalid role: {role}")

        if not content or not str(content).strip():
            raise PromptBuilderError("Message content cannot be empty.")
