# Generated by Django 6.0.5 on 2026-05-25 04:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier for the document.', primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='Human-readable title of the document.', max_length=1000, unique=True)),
                ('file', models.FileField(blank=True, help_text='Original uploaded legal document file.', null=True, upload_to='documents/%Y/%m/%d/')),
                ('document_type', models.CharField(choices=[('judgment', 'Judgment'), ('petition', 'Petition'), ('contract', 'Contract'), ('hearing', 'Hearing'), ('evidence', 'Evidence'), ('legal_notice', 'Legal Notice'), ('agreement', 'Agreement'), ('affidavit', 'Affidavit'), ('other', 'Other')], db_index=True, help_text='Categorization type of the legal document.', max_length=50)),
                ('case_id', models.CharField(blank=True, db_index=True, help_text='Optional external/internal case identifier associated with this document.', max_length=100, null=True)),
                ('extracted_text', models.JSONField(blank=True, help_text='Structured extracted content from OCR, parsers, or AI preprocessing pipelines.', null=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the document.', null=True)),
                ('keywords', models.JSONField(blank=True, help_text='AI extracted keywords, entities, citations, and tags.', null=True)),
                ('embedding_id', models.CharField(blank=True, db_index=True, help_text='Reference ID for vector database embedding storage.', max_length=255, null=True)),
                ('chunk_count', models.PositiveIntegerField(default=0, help_text='Number of semantic chunks generated for retrieval.')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current AI/RAG processing state.', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Stores processing failure logs or exception messages.', null=True)),
                ('is_vectorized', models.BooleanField(db_index=True, default=False, help_text='Indicates whether embeddings were successfully generated.')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Uploaded file size in bytes.', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='Detected MIME type of the uploaded file.', max_length=255, null=True)),
                ('language', models.CharField(default='en', help_text='Detected primary language of the document.', max_length=50)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Total number of pages in the document.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the document was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the document was last updated.')),
                ('owner', models.ForeignKey(help_text='User who uploaded or owns the document.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['processing_status'], name='documents_d_process_052924_idx'), models.Index(fields=['case_id'], name='documents_d_case_id_528e86_idx'), models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'), models.Index(fields=['owner', 'created_at'], name='documents_d_owner_i_db5cd3_idx')],
            },
        ),
    ]
