# Generated by Django 6.0.5 on 2026-05-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, help_text='Original uploaded legal document file.', upload_to='documents/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
