# Generated by Django 6.0.5 on 2026-05-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Original uploaded legal document file.', upload_to='docs/documents/%Y/%m/%d/'),
        ),
    ]
