# Generated by Django 6.0.5 on 2026-06-12 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('corporate', 'Corporate'), ('constitutional', 'Constitutional')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('closed', 'Closed')], default='open', max_length=30)),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('court_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('petitioner', 'Petitioner'), ('respondent', 'Respondent')], max_length=30)),
                ('advocate_name', models.CharField(blank=True, max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case')),
            ],
        ),
    ]
